version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development 
      SECRET_KEY: your_very_secret_key
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://flaskuser:flaskpassword@db/fitness_tracker
      # FLASK_APP is not strictly necessary with `python -m app` but can be useful for Flask CLI commands
      FLASK_APP: app
    volumes:
      - .:/app

  db:
    # It's recommended to use a specific version, not 'latest', for stability
    image: mariadb:latest
    container_name: mariadb-container-dev
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: fitness_tracker
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # This line is crucial for automatic database initialization by MariaDB
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  mariadb_data: